# Generated by Django 3.0.5 on 2020-04-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httpsrv', '0002_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='footer_left',
            field=models.TextField(default=''),
        ),
    ]
