# Generated by Django 3.0.5 on 2020-04-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httpsrv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='', max_length=65)),
                ('navbar_title', models.CharField(default='', max_length=65)),
                ('footer_left', models.CharField(default='', max_length=65)),
                ('column_left_color', models.CharField(default='', max_length=65)),
                ('column_mid_color', models.CharField(default='', max_length=65)),
                ('column_right_color', models.CharField(default='', max_length=65)),
            ],
        ),
    ]
